exports.deploySTC = require("./1_deploySTC")
exports.deployRecordLabel = require("./2_deployRecordLabel")
exports.approveSpender = require("./3_approveSpender")
exports.initializeArtistData = require("./4_initializeArtistData")
exports.simulateTwilio = require("./simulate-twilio")
